-- hyprfade.nvim now requires an explicit setup() call with opts.
-- See |hyprfade-configuration|.
-- Lazy.nvim users: add an `opts` table to your plugin spec;
-- lazy calls setup() automatically with those opts.
